import { mkdir, readFile, writeFile } from 'node:fs/promises';

// These are public, original editorial pages. Inventory and account data never enter them.
const origin = 'https://where-my-things.pages.dev';
// Public publisher ID, intentionally published; this is not an API secret.
const adsenseAccount = 'ca-pub-2685311477810917';
const accountMeta = `<meta name="google-adsense-account" content="${adsenseAccount}">`;
const adsenseHead = `${accountMeta}<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${adsenseAccount}" crossorigin="anonymous"></script>`;
const pages = {
  home: {
    slug: '', ko: ['어디뒀지? — 물건의 자리를 기억하는 방법', '찾기 전에, 둘 자리를 정해요.', '집 안 물품을 공간 → 방 → 가구 → 서랍으로 기록하는 방법과 직접 써볼 수 있는 물품 관리 데모입니다.'],
    en: ['Where Is It? — Give your belongings a place', 'A place for every little thing.', 'Learn to record belongings as space → room → furniture → drawer, then try the interactive inventory demo.'],
    sections: [
      {ko:['작은 서랍 하나부터 시작하세요','집 전체를 한 번에 입력하려 하면 금방 지칩니다. 오늘 자주 찾는 물건 5개가 있는 서랍 하나를 고르세요. 서랍에 이름을 붙이고 물품 이름, 수량, 정확한 위치를 기록하면 첫 보관 지도가 됩니다.','이 앱은 위치를 직접 확인하고 기록하는 도구입니다. 사진 속 물체의 이름을 AI가 제안할 수 있지만, 실제 보관 위치를 자동으로 알아내지는 못합니다.'], en:['Start with a single drawer','Choose one drawer containing five things you often look for. Give the drawer a clear name and record each item, quantity and exact location. That small map is a useful first step; you do not need to catalogue your entire home.','The app helps you record locations you have checked yourself. AI may suggest an object name from a photo, but it cannot discover where that object is stored.']},
      {ko:['지금 체험할 수 있는 것','물품 등록·검색·수정·삭제·이동, 계층형 위치 관리, 사진 선택, 한국어·영어 화면을 체험할 수 있습니다. 로그인 없이 모의 데이터를 이용해 둘러볼 수 있습니다.','현재 물품과 사진은 브라우저 메모리에만 있습니다. 새로고침, 탭 닫기, 로그아웃 또는 계정 전환 시 초기화됩니다. 영구 저장, 기기 간 동기화, 가족 초대는 아직 제공하지 않습니다. 중요한 물품의 유일한 기록으로 사용하지 마세요.'], en:['What you can try today','Create, search, edit, delete and move items; organise nested locations; select photos; and switch between Korean and English. The sample inventory works without signing in.','Items and photos currently live only in browser memory. Refreshing, closing the tab, signing out or switching accounts resets them. Persistent inventory storage, device sync and family invitations are not available yet. Keep important records separately.']},
      {ko:['목적에 맞게 읽어보세요','시작 가이드에는 위치 이름을 짓는 예시와 이동 후 기록하는 순서를 담았습니다. AI 가이드는 사진 촬영, 제안 수정, 본인 API 사용량 관리 방법을 설명합니다. 개인정보 안내에서는 현재 어떤 정보가 어디로 전달되는지 확인할 수 있습니다.'], en:['Find the help you need','The storage guide covers location names and the steps to follow after moving an item. The AI guide explains photo preparation, correcting suggestions and controlling personal API usage. The privacy page describes what information goes where.']}
    ]
  },
  guide: {
    slug:'guide', ko:['물품 정리 시작 가이드', '다시 찾을 수 있는 보관 지도 만들기', '서랍 하나부터 시작하는 위치 이름, 물품 입력, 이동 기록의 실제 예시입니다.'], en:['Storage guide', 'Build a map you can actually follow', 'Practical examples for naming locations, entering items and keeping track of moves.'],
    sections:[
      {ko:['1. 찾는 사람이 이해할 위치 이름','“위쪽”만 적으면 어느 가구의 위쪽인지 알기 어렵습니다. “우리 집 → 안방 → 화장대 → 맨 위 서랍”처럼 고정된 경로를 만드세요. 같은 방에 비슷한 가구가 두 개 있으면 “창가 책장”, “문 옆 책장”처럼 구분합니다.','서랍을 더 세분화할 때는 실제 구분이 있을 때만 하세요. 칸막이가 없다면 가상의 왼쪽·오른쪽을 나누는 것보다 서랍 하나에 함께 기록하는 편이 유지하기 쉽습니다.'], en:['1. Name locations another person can follow','“Top” is ambiguous. Use a stable path such as “Home → Bedroom → Dressing table → Top drawer”. Distinguish similar furniture with names such as “Bookcase by window” and “Bookcase by door”.','Only add a sublocation when there is a physical distinction. Without a divider, one drawer is often easier to maintain than imaginary left and right compartments.']},
      {ko:['2. 이름·태그·수량을 나누어 적기','이름은 물건을 구별하는 말, 태그는 함께 찾는 분류, 메모는 사용에 필요한 정보로 나눕니다. “검정 USB-C 충전 케이블 / 태그: 전자기기, 충전 / 수량: 2 / 메모: 노트북용”처럼 적으면 “충전”으로도 찾기 쉽습니다.','여권이나 열쇠는 사진 대신 “파란 여권 케이스”, “보조 열쇠”처럼 특징만 적어도 충분합니다. 번호, 출입 비밀번호, 신분증 내용은 물품 메모에 넣지 마세요.'], en:['2. Separate names, tags and quantities','Use the name to identify the item, tags to group related items, and notes for useful context. For example: “Black USB-C cable / tags: electronics, charging / quantity: 2 / note: for laptop”. A search for “charging” can then help you find it.','For passports or keys, a description such as “Blue passport cover” or “Spare key” may be enough. Avoid recording document numbers, entry codes or identity details.']},
      {ko:['3. 옮긴 직후 기록하기','물건을 실제 새 위치에 넣은 다음 상세 화면에서 이동을 선택하세요. 새 경로를 읽어보고 저장한 뒤, 같은 이름으로 검색해 경로가 바뀌었는지 확인합니다. 기록부터 바꾸고 물건을 나중에 옮기면 실제 위치와 어긋나기 쉽습니다.','위치를 삭제할 수 없다면 하위 위치나 남은 물품이 있는지 먼저 확인하세요. 물품을 옮기고 빈 하위 위치부터 정리하면 실수로 보관 경로를 잃는 일을 줄일 수 있습니다.'], en:['3. Record a move immediately afterwards','Put the item in its new place, open its details and choose Move. Read the new path before saving, then search for the item to check it. Updating the record before physically moving the item can leave the map out of step.','If a location cannot be deleted, check for remaining items and sublocations. Move the items and remove empty child locations first to avoid losing a useful path.']},
      {ko:['4. 첫 체험 확인표','데모에서 물품 하나를 등록하고 이름으로 검색합니다. 태그 검색도 해본 뒤 다른 서랍으로 이동해 경로를 확인하세요. 위치 이름을 수정하고 물품에 반영되는지도 확인합니다.','체험 기록은 새로고침하면 사라집니다. 실제 정리에서는 따로 보관한 기록과 비교하면서 일주일에 한 서랍씩 점검하는 방식으로 습관을 만들어 보세요.'], en:['4. Your first practice checklist','Add an item in the demo and search by its name. Try searching by a tag, then move it to another drawer and check the path. Rename the location and check that the item uses the updated name.','Demo changes disappear on refresh. For real organising, keep a separate durable record and review one drawer each week to build a manageable routine.']}
    ]
  },
  ai: {
    slug:'ai-guide', ko:['사진과 AI 사용 가이드', 'AI의 제안은 확인하고 저장하세요.', '사진 준비부터 수동 보정, 개인 Gemini API 사용량 제한까지 설명합니다.'], en:['Photo and AI guide', 'Check AI suggestions before saving.', 'Prepare photos, correct suggestions and understand the limits of personal Gemini API usage.'],
    sections:[
      {ko:['잘 보이는 물건 하나를 촬영하기','밝은 곳에서 물품 전체가 보이게 찍고 배경을 단순하게 합니다. 여러 물건이 겹쳐 있으면 이름이 섞일 수 있으므로 하나씩 촬영하세요. 반사되는 포장지는 각도를 조금 바꾸면 도움이 됩니다.','사진 선택만으로 실제 Gemini 분석이 실행되지는 않습니다. 분석 버튼과 모의 분석 표시를 확인하세요. 원본 대신 긴 변 1,024px 이하, 512KiB 이하의 JPEG 복사본을 분석에 보냅니다. 민감한 문서나 얼굴이 포함된 사진은 선택하지 마세요.'], en:['Photograph one clearly visible object','Use good light, include the entire object and keep the background simple. Photograph overlapping items separately to avoid mixed suggestions. A small change in angle may reduce reflections on packaging.','Selecting a photo alone does not run Gemini. Check the analysis button and demo label. Analysis uses a JPEG copy up to 1,024 pixels on its longest side and 512 KiB, rather than the original. Avoid images containing sensitive documents or faces.']},
      {ko:['이름과 태그를 직접 검토하기','AI가 “충전기”라고 제안해도 실제로는 변환 어댑터일 수 있습니다. 제안된 이름과 태그를 물품과 비교해 수정한 뒤 등록하세요. 색상이나 용도를 덧붙이면 비슷한 물건을 구분하기 쉽습니다.','AI는 사진 밖의 서랍이나 집 안 위치를 판단하지 못합니다. 위치는 직접 선택해야 합니다. 화면 언어를 바꾸면 다음 분석의 결과 언어가 바뀌며 기존 물품 이름은 자동 번역되지 않습니다.'], en:['Review names and tags yourself','An object labelled “charger” may actually be an adapter. Compare the suggestions with the real item and correct them before saving. Adding a colour or purpose can distinguish similar objects.','AI cannot determine a drawer or room outside the image. Choose the location yourself. Switching the interface language changes the language of the next analysis; it does not translate existing item names.']},
      {ko:['본인의 API로 필요한 때만 분석','실제 분석에는 앱 회원 계정과 본인의 Gemini API 키가 필요하며 운영자의 Supabase 설정도 완료되어야 합니다. 키는 서버에서 암호화해 보관하고 브라우저 코드나 GitHub에 넣지 않습니다. 설정이 없는 배포에서는 데모를 이용할 수 있습니다.','현재 계정당 하루 20회 시도, 요청 사이 20초 간격, 동시 1건을 적용합니다. 같은 이미지·모델·키 버전·언어의 성공 결과는 24시간 캐시하며 출력은 최대 256토큰입니다. 자동 재시도는 하지 않습니다.'], en:['Use your own API only when needed','Live analysis requires an app account, your own Gemini API key and a configured Supabase backend. Keys are encrypted on the server and never put in browser source or GitHub. Deployments without backend configuration still support the demo.','The current limits are 20 attempts per account per day, a 20-second interval and one active request. Successful results for the same image, model, key version and language are cached for 24 hours. Output is capped at 256 tokens; there are no automatic retries.']},
      {ko:['실패하거나 한도에 도달했을 때','한도 메시지가 나오면 반복 클릭하지 말고 이름과 태그를 직접 입력하세요. 사진이 불명확하면 재촬영하되 필요할 때만 새 분석을 요청합니다. 키를 교체하거나 언어를 바꾸면 이전 캐시가 재사용되지 않을 수 있습니다.','앱의 제한은 Google 계정의 결제 한도와 별개입니다. 무료 할당량과 요금은 본인의 제공업체 콘솔에서 확인하세요. 앱이 결제를 활성화하지는 않으며 실제 분석 비용은 사용자의 API 계정 정책에 따릅니다.'], en:['When a request fails or reaches a limit','If a limit message appears, enter names and tags manually instead of repeatedly clicking. Retake an unclear photo and request another analysis only when needed. Changing a key or language may prevent reuse of an earlier cached result.','App limits are separate from billing limits on your Google account. Check free allowances and pricing in your provider console. The app does not enable billing; any live analysis charges follow your API account settings.']}
    ]
  },
  privacy: {
    slug:'privacy', ko:['개인정보와 데이터 안내', '내 기록은 어디에 남을까요?', '현재 버전의 메모리 저장, 로그인 정보, 사진 분석과 API 키 처리 범위를 안내합니다.'], en:['Privacy and data', 'Where does your information go?', 'How this version handles demo inventory, sign-in, photo analysis and API keys.'],
    sections:[
      {ko:['데모 물품·사진·언어 설정','물품, 위치, 선택한 사진은 현재 탭의 메모리에 저장되며 영구 저장하거나 다른 기기로 동기화하지 않습니다. 화면 언어 설정만 이 브라우저의 로컬 저장소에 남습니다. 공유 기기에서는 브라우저 설정에서 사이트 데이터를 지울 수 있습니다.','사진 파일을 선택하면 현재 화면에 미리보기가 표시됩니다. 실제 AI 분석을 요청한 경우에만 축소된 이미지가 Supabase 서버를 거쳐 Google Gemini로 전달됩니다. 개인 기록이나 업로드 사진을 공개 안내 페이지에 게시하지 않습니다.'], en:['Demo inventory, photos and language preference','Items, locations and selected photos remain in the current tab’s memory, without persistent storage or device sync. Only the language preference is saved locally. On shared devices you can clear site data in your browser settings.','Selecting a photo displays a local preview. A reduced image is sent through the Supabase server to Google Gemini only when you request live AI analysis. Personal inventory and uploaded photos are not published on these information pages.']},
      {ko:['로그인과 개인 API 키','백엔드가 설정된 배포에서 이메일과 비밀번호는 Supabase 인증에 사용됩니다. 로그인 세션은 브라우저에 유지될 수 있으므로 공용 기기에서는 로그아웃하세요. 앱 계정은 Supabase 관리 대시보드 계정과 별개입니다.','등록한 Gemini 키는 서버에서 암호화하여 저장됩니다. 계정 설정에서 키를 삭제할 수 있습니다. 분석 캐시에는 이미지 지문, 제안 결과, 사용량 정보 등이 보관되며 캐시 재사용 유효기간은 24시간입니다. 이는 만료 시 데이터가 즉시 자동 삭제된다는 의미가 아닙니다.'], en:['Sign-in and personal API keys','On configured deployments, email and password are used by Supabase authentication. A session may persist in the browser, so sign out on shared devices. App accounts are separate from Supabase dashboard accounts.','Gemini keys are encrypted on the server and can be removed through account settings. Analysis records include image fingerprints, suggestions and usage information. Cached results are reusable for 24 hours; expiry does not mean immediate automatic deletion of stored records.']},
      {ko:['외부 서비스와 문의','웹사이트 호스팅은 Cloudflare, 설정된 인증과 분석 서버는 Supabase, 실제 물체 분석은 Google Gemini를 사용합니다. 이들 제공업체는 서비스 운영 과정에서 접속 정보와 기술 로그를 처리할 수 있습니다. 앱 소스에서 IP를 제거하는 것과 호스팅 업체의 접속 기록은 다릅니다.','공개 안내 페이지에 Google AdSense 광고 코드를 포함합니다. Google과 광고 파트너는 광고 제공·측정·개인 최적화를 위해 쿠키, 웹 비콘, IP 주소와 기기·접속 정보를 처리할 수 있습니다. 개인 물품 관리·로그인 화면과 오류 페이지에는 광고 스크립트를 넣지 않습니다. 개인정보 관련 문의는 아래 GitHub 문의 경로에서 민감한 정보 없이 접수하세요. 공개 이슈에 비밀번호, API 키, 이메일 주소, 개인 사진을 올리지 마세요.'], en:['Service providers and questions','Cloudflare hosts the site; Supabase handles configured authentication and analysis endpoints; Google Gemini performs live object recognition. Providers may process connection data and technical logs. Removing IP addresses from source does not remove hosting access logs.','Public information pages include Google AdSense code. Google and advertising partners may use cookies, web beacons, IP addresses and device or connection information for ad delivery, measurement and personalisation. The inventory, sign-in and error screens do not include advertising scripts. Use the GitHub contact link below for questions without including sensitive information. Never post passwords, API keys, email addresses or personal photos in public issues.']}
    ]
  },
  about: {
    slug:'about', ko:['서비스 소개와 문의', '어디뒀지?를 만드는 이유', '물건을 다시 찾는 데 도움이 되는 작은 기록 도구를 만들고 있습니다.'], en:['About and contact', 'Why we are building Where Is It?', 'A small tool to help you find belongings through clear, useful records.'],
    sections:[
      {ko:['목표와 현재 상태','집과 공동 공간에서 물품의 이름만 기억하고 위치를 잊는 문제를 줄이는 것이 목표입니다. 검색할 수 있는 이름과 실제 장소를 연결하고, 사진 인식은 입력을 돕는 보조 기능으로 사용합니다.','현재 공개 버전은 물품 관리 데모와 선택적으로 연결하는 로그인·개인 API 기능을 제공합니다. 영구 물품 저장, 비공개 사진 보관소, 기기 동기화, 구성원 초대는 아직 구현하지 않았습니다. 안내 내용은 현재 코드의 동작을 기준으로 작성했습니다.'], en:['Purpose and current status','We aim to reduce the frustration of remembering an item’s name but forgetting its location. The tool links searchable descriptions to real places, with photo recognition assisting data entry.','This public version offers an inventory demo and optional sign-in with personal API features. Persistent inventory, private photo storage, device sync and member invitations are not implemented. These guides describe current code behaviour.']},
      {ko:['운영·개발과 피드백','프로젝트는 GitHub의 HG0395/where-my-things에서 관리합니다. 오류나 개선 의견은 공개 이슈로 접수할 수 있습니다. “어느 화면에서 무엇을 했는지, 예상한 결과와 실제 결과”를 적으면 확인에 도움이 됩니다.','예시: “물품을 새 서랍으로 이동한 뒤 이름으로 검색했는데 이전 경로가 보입니다.” 화면 사진을 첨부한다면 물품 이름, 개인 정보, API 키가 노출되지 않았는지 먼저 확인하세요. 응답 시간이나 해결을 보장하지는 않습니다.'], en:['Development and feedback','The project is maintained at HG0395/where-my-things on GitHub. Report bugs or suggestions as public issues. Include the screen, action, expected result and actual result so the problem can be reproduced.','For example: “After moving an item to a new drawer, searching its name still shows the old path.” Before attaching a screenshot, remove personal details, private item names and API keys. Response times and resolution are not guaranteed.']},
      {ko:['콘텐츠와 광고 원칙','정리 방법과 실제 사용에 필요한 안내를 직접 작성하고, 동일한 내용을 여러 페이지에 반복해 늘리지 않습니다. 가이드에서 데모로 바로 이동할 수 있으며 로그인이나 광고 보기를 강요하지 않습니다.','공개 안내 페이지에 AdSense 코드를 연결했습니다. 실제 광고 표시는 Google 심사와 계정 설정에 따릅니다. 개인 보관함, 로그인, 오류 화면에는 광고 스크립트를 추가하지 않습니다. 이 개선은 AdSense 승인이나 수익을 보장하지 않습니다.'], en:['Content and advertising principles','The guides are written for this tool and focus on practical organising. We avoid padding the site with repeated pages. You can go directly from a guide to the demo without a required login or ad view.','Public information pages include AdSense code. Actual ad display depends on Google review and account settings. Inventory, sign-in and error screens do not include advertising scripts. These improvements do not guarantee AdSense approval or revenue.']}
    ]
  }
};
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
pages.privacy.sections.push({
  ko: ['광고 쿠키와 선택', 'Google은 이 사이트와 다른 사이트의 방문 정보를 바탕으로 광고를 제공할 수 있습니다. Google 광고 설정에서 개인 맞춤 광고를 관리하고 브라우저에서 쿠키를 제한하거나 삭제할 수 있습니다. 쿠키 제한은 사이트 로그인이나 광고 동작에 영향을 줄 수 있습니다.', 'EEA·영국·스위스 방문자에게 광고를 제공하려면 운영자가 Google 인증 CMP를 구성하여 해당 지역의 동의 요건을 충족해야 합니다. 현재 코드에 별도의 CMP를 구현했다는 의미는 아닙니다.'],
  en: ['Advertising cookies and choices', 'Google may serve ads based on visits to this and other sites. Manage personalised ads in Google ad settings, or limit and delete cookies in your browser. Cookie restrictions may affect sign-in or advertising behaviour.', 'Before serving ads to visitors in the EEA, UK or Switzerland, the operator must configure a Google-certified CMP to meet regional consent requirements. This code does not itself implement a separate CMP.']
});
const pathFor = (page, lang) => `/${lang === 'en' ? 'en/' : ''}${page.slug ? page.slug + '/' : ''}`;
const css = `:root{font-family:'Malgun Gothic','Segoe UI',system-ui,sans-serif;color:#203b36;background:#f7f9f7;line-height:1.8}*{box-sizing:border-box}body{margin:0}a{color:#126650;text-underline-offset:4px}a:focus-visible{outline:3px solid #b27622;outline-offset:4px}header,main,footer{max-width:1040px;margin:auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap;border-bottom:1px solid #dbe5df}.brand{font-size:24px;font-weight:800;text-decoration:none}nav{display:flex;flex-wrap:wrap;gap:12px 20px;font-size:14px}nav [aria-current=page]{font-weight:bold}main{padding-top:64px;padding-bottom:64px}h1{font-size:clamp(30px,5vw,52px);letter-spacing:-1.5px;line-height:1.25;max-width:820px}h2{font-size:23px;line-height:1.5;margin:0 0 16px}p{margin:0 0 16px}.eyebrow{color:#277761;font-size:13px;font-weight:bold;letter-spacing:2px}.lead{font-size:19px;max-width:740px;margin:24px 0}.actions{display:flex;flex-wrap:wrap;gap:12px;margin:28px 0 44px}.cta{display:inline-block;background:#196d54;color:white;padding:12px 23px;border-radius:10px;text-decoration:none;font-weight:700}.secondary{background:white;color:#196d54;border:1px solid #b6d1c3}.notice{padding:18px 22px;background:#fff4da;border-left:4px solid #d6a64b;border-radius:6px;margin-bottom:36px}section{padding:30px;background:white;border:1px solid #dfe7e1;border-radius:16px;margin:22px 0;max-width:850px}section p:last-child{margin-bottom:0}.links{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;margin:32px 0}.links a{background:#eaf2ed;border-radius:12px;padding:22px;font-weight:700;text-decoration:none}footer{border-top:1px solid #dbe5df;font-size:14px}footer p{margin-top:18px;color:#587168}@media(max-width:520px){header,main,footer{padding:20px}main{padding-top:38px}section{padding:22px}nav{gap:10px 16px}.lead{font-size:17px}}`;
function render(key, page, lang) {
 const [title, heading, intro] = page[lang];
 const en = lang === 'en';
 const nav = Object.entries(pages).map(([id,p]) => `<a href="${pathFor(p,lang)}"${id===key?' aria-current="page"':''}>${escape(p[lang][0].split(' — ')[0])}</a>`).join('');
 return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(intro)}"><link rel="icon" href="/favicon.svg"><link rel="canonical" href="${origin}${pathFor(page,lang)}"><link rel="alternate" hreflang="ko" href="${origin}${pathFor(page,'ko')}"><link rel="alternate" hreflang="en" href="${origin}${pathFor(page,'en')}"><link rel="stylesheet" href="/site.css"></head><body><header><a class="brand" href="${pathFor(pages.home,lang)}">${en?'Where Is It?':'어디뒀지?'}</a><nav aria-label="${en?'Main navigation':'주 메뉴'}">${nav}<a href="${pathFor(page,en?'ko':'en')}" lang="${en?'ko':'en'}">${en?'한국어':'English'}</a></nav></header><main><p class="eyebrow">A LITTLE MAP FOR YOUR THINGS</p><h1>${escape(heading)}</h1><p class="lead">${escape(intro)}</p><div class="actions"><a class="cta" href="/app/">${en?'Try inventory demo':'물품 관리 체험하기'}</a><a class="cta secondary" href="${pathFor(pages.guide,lang)}">${en?'Read the storage guide':'정리 가이드 읽기'}</a></div><p class="notice">${en?'Demo: inventory changes reset on refresh. Sign-in does not enable inventory sync.':'데모 안내: 물품 변경은 새로고침하면 초기화됩니다. 로그인해도 물품이 동기화되지는 않습니다.'}</p>${page.sections.map(s=>`<section><h2>${escape(s[lang][0])}</h2>${s[lang].slice(1).map(p=>`<p>${escape(p)}</p>`).join('')}</section>`).join('')}<div class="links">${Object.entries(pages).filter(([id])=>id!==key).map(([,p])=>`<a href="${pathFor(p,lang)}">${escape(p[lang][0])} →</a>`).join('')}</div></main><footer><nav aria-label="${en?'Project links':'프로젝트 링크'}"><a href="https://github.com/HG0395/where-my-things">${en?'Source code':'소스 코드'}</a><a href="https://github.com/HG0395/where-my-things/issues">${en?'Contact & report an issue (public)':'문의·오류 신고 (공개)'}</a><a href="${pathFor(pages.privacy,lang)}">${en?'Privacy and data':'개인정보와 데이터'}</a></nav><p>${en?'Current version: inventory demo + optional personal API analysis. Public pages include AdSense code.':'현재 버전: 물품 관리 데모 + 선택적 개인 API 분석. 공개 안내 페이지에 AdSense 코드를 포함합니다.'}</p></footer></body></html>`;
}
const app = await readFile('dist/index.html', 'utf8');
if (app.includes('/src/main.tsx') || !app.includes('/assets/')) throw new Error('Expected a compiled Vite app. Run npm run build.');
await mkdir('dist/app', {recursive:true});
await writeFile('dist/app/index.html', app.replace('<head>', `<head>${accountMeta}<meta name="robots" content="noindex">`));
await writeFile('dist/site.css', css);
const urls = [];
for (const lang of ['ko','en']) for (const [key,page] of Object.entries(pages)) {
 const path = pathFor(page,lang);
 await mkdir(`dist${path}`, {recursive:true});
 let html = render(key,page,lang).replace('</head>', `${adsenseHead}</head>`);
 if (key === 'privacy') html = html.replace('</main>', `<section><h2>${lang === 'en' ? 'Google privacy and advertising controls' : 'Google 개인정보 및 광고 설정'}</h2><p><a href="https://policies.google.com/technologies/partner-sites?hl=${lang}">${lang === 'en' ? 'How Google uses information from partner sites' : 'Google의 파트너 사이트 정보 사용 방식'}</a></p><p><a href="https://myadcenter.google.com/">${lang === 'en' ? 'Manage Google ad preferences' : 'Google 광고 설정 관리'}</a></p></section></main>`);
 await writeFile(`dist${path}index.html`, html);
 urls.push(`${origin}${path}`);
}
await writeFile('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(url=>`<url><loc>${url}</loc></url>`).join('')}</urlset>`);
await writeFile('dist/404.html', '<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>페이지를 찾을 수 없어요 | 어디뒀지?</title><link rel="stylesheet" href="/site.css"><main><h1>페이지를 찾을 수 없어요.</h1><p>This page could not be found.</p><a href="/">홈으로 / Home</a> · <a href="/app/">물품 관리 / Inventory</a></main></html>');
console.log(`Built ${urls.length} public pages, inventory app and a real 404 page in dist.`);
